name: Ruff lint & format check

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "ruff.toml"
      - ".github/workflows/ruff.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - "ruff.toml"
      - ".github/workflows/ruff.yml"

jobs:
  ruff:
    name: Run Ruff checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github ngbs-api"

      - name: Check Ruff formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff ngbs-api"
